# Generated by Django 5.1.1 on 2024-09-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortifolioOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='owner/')),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('whatsapp', models.URLField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('about_me', models.TextField()),
                ('contact_me', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.CharField(max_length=200)),
                ('demo', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
