# Generated by Django 5.1.1 on 2024-09-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portifolioowner',
            name='name',
        ),
        migrations.AddField(
            model_name='portifolioowner',
            name='first_name',
            field=models.CharField(default='Matheus', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portifolioowner',
            name='last_name',
            field=models.CharField(default='Matheus', max_length=60),
            preserve_default=False,
        ),
    ]
