# Generated by Django 5.1.1 on 2024-09-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_portifolioowner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolioowner',
            name='your_stack',
            field=models.CharField(default='Django Backend Developer - Angular & NextJs', max_length=120),
            preserve_default=False,
        ),
    ]
