# Generated by Django 5.1.1 on 2025-06-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_is_published_service_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolioowner',
            name='full_name',
            field=models.CharField(default='math', max_length=60),
            preserve_default=False,
        ),
    ]
