# Generated by Django 5.1.1 on 2025-06-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_portifolioowner_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolioowner',
            name='youtube_url',
            field=models.URLField(default='www.youtube.com'),
            preserve_default=False,
        ),
    ]
