# Generated by Django 5.1.1 on 2025-06-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_portifolioowner_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioowner',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
