# Generated by Django 5.1.1 on 2025-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_portifolioowner_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioowner',
            name='contact_me',
            field=models.EmailField(max_length=254),
        ),
    ]
